import fs from 'node:fs/promises';
const [url,port]=process.argv.slice(2),target=await(await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(url)}`,{method:'PUT'})).json(),ws=new WebSocket(target.webSocketDebuggerUrl.replace('localhost','127.0.0.1'));
await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});
let id=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)});
function call(method,params={}){return new Promise((resolve,reject)=>{const serial=++id,timer=setTimeout(()=>reject(Error('Timeout '+method)),15000);pending.set(serial,{resolve:r=>{clearTimeout(timer);resolve(r)},reject:e=>{clearTimeout(timer);reject(e)}});ws.send(JSON.stringify({id:serial,method,params}))})}
async function evalJS(code){const r=await call('Runtime.evaluate',{expression:`(async()=>{${code}})()`,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function wait(code){for(let n=0;n<100;n++){if(await evalJS('return '+code))return;await new Promise(r=>setTimeout(r,100))}throw Error('Wait '+code)}
async function screenshot(name){await evalJS(`await Promise.all([...document.images].filter(i=>i.getClientRects().length).map(i=>i.decode().catch(()=>{})));`);const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile('artifacts/card-review-'+name+'.png',Buffer.from(r.data,'base64'))}
async function reset(s){await evalJS(`await act({action:'reset',scenario:'${s}'});`)}
try{
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1500,height:1050,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url});await wait(`typeof state!=='undefined'&&!!state`);
 await evalJS(`if(state.battle.players.length!==2)throw Error('Not a duel');if(document.querySelectorAll('.hand .card').length!==5)throw Error('Hand count');if(document.querySelector('.mana-plaque').textContent!=='Current Mana: 5/10')throw Error('Mana plaque');if(document.querySelectorAll('.central-mana .mana-artifact.lit').length!==5||document.querySelectorAll('.central-mana .mana-artifact:not(.lit)').length!==5)throw Error('Mana track');if(!document.querySelector('.hand').textContent.includes('Media formation')||!document.querySelector('.hand').textContent.includes('Pnited Front'))throw Error('Reference labels');if(state.battle.players.find(p=>p.id!==state.viewer).hand.length)throw Error('Private hand leak');if(!document.querySelector('.pile-count').textContent.includes('6'))throw Error('Token pile count');if(document.querySelector('#pass').textContent!=='Go to combat')throw Error('Combat progression label');`);
 await evalJS(`await act({action:'auto_responses',enabled:false});`);
 await evalJS(`if(!document.querySelector('#motion-controls'))throw Error('Motion settings missing');document.querySelector('#reduce-motion').checked=true;document.querySelector('#reduce-motion').dispatchEvent(new Event('change'));if(!document.body.classList.contains('reduced-motion'))throw Error('Reduced motion ignored');document.querySelector('#reduce-motion').checked=false;document.querySelector('#reduce-motion').dispatchEvent(new Event('change'));`);
 await screenshot('table');await call('Emulation.setDeviceMetricsOverride',{width:1920,height:880,deviceScaleFactor:1,mobile:false});await screenshot('wide-table');await call('Emulation.setDeviceMetricsOverride',{width:1500,height:1050,deviceScaleFactor:1,mobile:false});
 await evalJS(`document.querySelector('#pass').click();`);await wait('!busy&&state.battle.priority===1');await evalJS(`if(state.battle.phase!=='main'||document.querySelector('#pass').textContent!=='Pass priority')throw Error('Opponent main-phase response skipped');await act({action:'pass'});if(state.battle.phase!=='precombat'||document.querySelector('#pass').textContent!=='Continue to combat')throw Error('Precombat window missing');await act({action:'pass'});await act({action:'pass'});if(state.battle.phase!=='combat'||!document.querySelector('#attack'))throw Error('Cannot enter combat');`);await reset('main');
 await reset('grow');await evalJS(`if(document.querySelector('.resource-piles'))throw Error('Decorative lands remain');const buttons=[...document.querySelectorAll('[data-gem]')];if(buttons.map(b=>b.dataset.gem).join('')!=='WU')throw Error('Gem choice ignores identity');document.querySelector('[data-gem="U"]').click();`);await wait('!busy&&state.battle.phase==="main"');await evalJS(`if(state.battle.players[0].capacity.U!==3||state.battle.players[0].mana.U!==3)throw Error('Gem did not add usable capacity');if(!document.querySelector('.player:not(.own) .mana-artifact.U'))throw Error('Opponent gems missing');`);await reset('main');
 // Multiple ability choices and touch information control do not activate an ability.
 await evalJS(`const c=state.battle.players[0].board[0];choices(c,document.querySelector('[data-uid="'+c.uid+'"]'));if(!document.querySelector('#choices').hidden)throw Error('Only one available action should directly select');if(!selected||selected.ability!==0)throw Error('Main ability not selected');cancel();`);
 await reset('combat');await evalJS(`const c=state.battle.players[0].board[1];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));if(document.querySelector('#choices').hidden||!document.querySelector('#choices').textContent.includes('Attack'))throw Error('Attack/Ability choice missing');document.querySelector('#choices [data-info]').click();if(!document.querySelector('.ability-description.expanded'))throw Error('Ability info did not expand');if(state.battle.stack.length)throw Error('Info activated an ability');`);await screenshot('combat-choice');
 await evalJS(`document.querySelector('#choices [data-option="1"]').click();if(!selected)throw Error('Ability targeting missing');const c=state.battle.players[0].board[2];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));if(!document.querySelector('#arrow-lines path'))throw Error('Target arrow missing');if(state.battle.stack.length)throw Error('Target spent resources before confirmation');inspect(c);if(!document.querySelector('#inspect').open)throw Error('Persistent inspect missing');`);
 await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});await evalJS(`if(!selected||document.querySelector('#inspect').open)throw Error('Escape did not preserve target');document.querySelector('#confirm').click();`);await wait('!busy&&state.battle.stack.length===1');await evalJS(`if(document.querySelector('#arrow-lines path'))throw Error('Targeting arrow persisted after confirmation');if(state.battle.players.length!==2)throw Error('Not a duel');`);
 await reset('response');await evalJS(`const c=state.battle.players[0].board[0];if(!c.abilities[1].available||c.abilities[0].available)throw Error('Response timing');chooseAbility(c,1);selected.target=state.battle.players[0].board[1].uid;render();await confirm();`);await wait('!busy&&state.battle.stack.length===2');
 await evalJS(`for(let n=0;n<4;n++)await act({action:'pass'});if(state.battle.players[0].board[1].damage!==0)throw Error('Protection failed to respond');`);
 await reset('invalid');await evalJS(`const c=state.battle.players[0].hand.find(c=>c.id==='u_return');onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));selected.target=state.battle.players[0].board[1].uid;render();await confirm();`);await wait('!busy&&state.battle.stack.length===2');await evalJS(`for(let n=0;n<4;n++)await act({action:'pass'});if(!state.battle.log.some(x=>x.includes('fizzles')))throw Error('Invalid target did not fizzle');`);
 await reset('blocks');await evalJS(`const c=state.battle.players[0].board[1];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));if(!document.querySelector('#choices').textContent.includes('Block'))throw Error('Block/Ability missing');`);
 await reset('buffs');const box=await evalJS(`const c=state.battle.players[0].board[1],node=document.querySelector('.board [data-uid="'+c.uid+'"]');if(!node.querySelector('.buff-icons').textContent.includes('+1'))throw Error('Overflow effects missing');const r=node.getBoundingClientRect();return {x:r.x+40,y:r.y+50}`);await call('Input.dispatchMouseEvent',{type:'mouseMoved',...box});await new Promise(r=>setTimeout(r,650));await evalJS(`if(document.querySelector('#hover').hidden)throw Error('Hover failed');if(!document.querySelector('#hover .buff-panel').textContent.includes('Source:'))throw Error('Buff metadata missing');const r=document.querySelector('#hover .inspection-group').getBoundingClientRect();if(Math.abs(r.left+r.width/2-document.documentElement.clientWidth/2)>2)throw Error('Inspection not centered');`);await screenshot('buff-inspection');
 await call('Emulation.setDeviceMetricsOverride',{width:850,height:950,deviceScaleFactor:1,mobile:false});await evalJS(`hideHover();if(!getComputedStyle(document.body).backgroundImage.includes('temple-table'))throw Error('Temple background missing');`);await screenshot('narrow-table');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await evalJS(`hideHover();inspect(state.battle.players[0].board[1]);if(document.documentElement.scrollWidth>innerWidth+1)throw Error('Mobile horizontal overflow');const c=document.querySelector('#inspect .card').getBoundingClientRect(),b=document.querySelector('#inspect .buff-panel').getBoundingClientRect();if(b.top<c.bottom-2)throw Error('Mobile buffs not below card');`);await screenshot('mobile-inspection');

 await call('Emulation.setDeviceMetricsOverride',{width:1920,height:880,deviceScaleFactor:1,mobile:false});
 await reset('fire');await evalJS(`motionSettings.reduced=false;SpireFX.configure({reduced:false});const c=state.battle.players[0].hand[0];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));`);
 await call('Input.dispatchMouseEvent',{type:'mousePressed',x:1500,y:200,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:1500,y:200,button:'left',clickCount:1});
 await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:1120,y:305});await wait('SpireFX.activeCrackle');await new Promise(r=>setTimeout(r,150));await evalJS(`if(document.querySelector('.fx-art-fire,.fx-art-aura,.spell-scorch'))throw Error('Target preview showed an impact');if(!SpireFX.activeCrackle)throw Error('Flame crackle missing after gesture '+JSON.stringify(SpireFX.debug));selected.target=state.battle.players[1].board[0].uid;render();hideHover();`);await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:1420,y:280});await evalJS(`hideHover();`);await new Promise(r=>setTimeout(r,120));await screenshot('fire-targeting');
 await evalJS(`window.expectedFireOrigin=SpireFX.locate(selected.uid,0);await confirm();if(!SpireFX.activeCrackle)throw Error('Pending fire charge lost its crackle');if(!document.querySelector('.fx-pending-flame'))throw Error('Cast did not automatically create the flame charge');if(!document.querySelector('.fx-pending-flame').getAnimations().length)throw Error('Cast flame is not animated');await act({action:'pass'});await act({action:'pass'});`);await wait("!!document.querySelector('.spell-scorch')");await evalJS(`if(!document.querySelector('.spell-scorch'))throw Error('Burnt impact missing');if(!SpireFX.stats.impacts)throw Error('Impact never played');if(Math.hypot(SpireFX.stats.lastLaunch.from.x-expectedFireOrigin.x,SpireFX.stats.lastLaunch.from.y-expectedFireOrigin.y)>2)throw Error('Fireball did not launch from the hand card');`);await screenshot('fire-impact');
 await new Promise(r=>setTimeout(r,3400));await evalJS(`if(document.querySelector('.spell-scorch'))throw Error('Scorch did not expire');`);
 await reset('meteors');await evalJS(`const c=state.battle.players[0].hand[0];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));await new Promise(r=>setTimeout(r,200));if(!SpireFX.debug.weather||SpireFX.debug.family!=='meteor'||SpireFX.activeCrackle)throw Error('Meteor selection still behaves like fireball');await confirm();await act({action:'pass'});await act({action:'pass'});if(SpireFX.stats.meteors<20)throw Error('Meteor shower does not cover the battlefield');`);await new Promise(r=>setTimeout(r,300));await screenshot('meteor-rain');
 await evalJS(`SpireFX.configure({sound:false});if(SpireFX.activeCrackle)throw Error('Mute ignored');SpireFX.clear();if(SpireFX.activeParticles||document.querySelector('.spell-scorch'))throw Error('FX cleanup failed');`);
 await evalJS(`SpireFX.configure({sound:false,reduced:false});await act({action:'reset',scenario:'summon',presentation:true});await act({action:'auto_responses',enabled:false});const c=state.battle.players[0].hand[0];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));await confirm();if(!document.querySelector('.fx-arrival-card'))throw Error('Missing pending creature');const count=state.battle.players[0].board.length;await act({action:'pass'});if(state.viewer!==0)throw Error('Camera changed');await act({action:'review_reply'});if(state.battle.players[0].board.length!==count+1||!SpireFX.stats.arrivals)throw Error('Creature did not arrive');`);
 await new Promise(r=>setTimeout(r,700));await screenshot('creature-arrival');
 await evalJS(`await act({action:'reset',scenario:'commanderarrival',presentation:true});document.querySelector('#cast-commander').click();await confirm();if(!document.querySelector('.fx-arrival-card'))throw Error('Missing pending commander');await act({action:'pass'});await act({action:'review_reply'});if(!SpireFX.stats.commanderArrivals)throw Error('Commander entrance missing');`);
 await new Promise(r=>setTimeout(r,700));await screenshot('commander-arrival');
 await evalJS(`await act({action:'reset',scenario:'arrivalcounter',presentation:true});const count=state.battle.players[0].board.length;await act({action:'review_reply'});await act({action:'review_reply'});await act({action:'pass'});if(state.battle.players[0].board.length!==count)throw Error('Countered creature entered');`);await wait('SpireFX.stats.counters>0');await evalJS(``);
 await evalJS(`await act({action:'reset',scenario:'combatanim',presentation:true});const a=state.battle.attacks[0].uid,c=state.battle.players[0].board[0];await act({action:'block',blocks:{[a]:[c.uid]}});for(let i=0;i<6&&!SpireFX.stats.combatSequences;i++)await act({action:state.battle.priority===0?'pass':'review_reply'});if(!SpireFX.stats.combatSequences)throw Error('Blocked combat animation missing');`);
 await evalJS(`await new Promise(r=>setTimeout(r,195));const numbers=[...document.querySelectorAll('.fx-state-number')].map(n=>n.textContent);if(numbers.filter(t=>t.startsWith('−')).length<2)throw Error('Blocked combat did not show both damage outcomes');if([...document.querySelectorAll('.player .board')].some(n=>n.getAnimations().some(a=>a.effect.getKeyframes().some(f=>f.translate&&f.translate!=='0px'))))throw Error('Ordinary hit shook whole rows');if(SpireFX.debug.queued)throw Error('Combat blocked newer presentation');`);
 await screenshot('combat-impact');await new Promise(r=>setTimeout(r,750));await evalJS(`if(document.querySelector('.fx-departing-card,.fx-state-number'))throw Error('Combat exceeded its presentation budget');`);


 // Real public-event resolution for each non-fire animation, including pending and cleanup.
 const families={wisdom:'wisdom',counterseal:'counter',shadow:'shadow',revival:'portal',growth:'growth',roots:'roots',shatter:'shatter',rally:'rally'};
 for(const [scene,family] of Object.entries(families)){
  await evalJS(`SpireFX.configure({sound:false,reduced:false,intensity:1});await act({action:'reset',scenario:'${scene}',presentation:true});await act({action:'auto_responses',enabled:false});globalThis.familyBefore=SpireFX.stats.families['${family}']||0;const c=state.battle.players[0].hand[0];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));if(!selected)throw Error('Cannot select ${scene}');if(selected.targets.length)selected.target=selected.targets[0];render();await confirm();if(!document.querySelector('.fx-pending-sigil[data-family="${family}"]'))throw Error('Missing ${scene} pending charge');`);
  await screenshot(scene+'-pending');
  await evalJS(`await act({action:'pass'});await act({action:'review_reply'});`);
  await wait(`(SpireFX.stats.families['${family}']||0)>familyBefore`);
  await screenshot(scene+'-impact');
  await evalJS('SpireFX.clear();if(document.querySelectorAll(".fx-pending-sigil,.fx-art-aura").length||SpireFX.activeParticles)throw Error("Family FX leaked after cleanup")');
 }
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await evalJS(`await act({action:'reset',scenario:'growth',presentation:true});SpireFX.configure({reduced:true,sound:false});const c=state.battle.players[0].hand[0];onCard(c,document.querySelector('[data-uid="'+c.uid+'"]'));selected.target=selected.targets[0];render();await confirm();await act({action:'pass'});await act({action:'review_reply'});if(document.documentElement.scrollWidth>innerWidth+1)throw Error('Mobile effect review overflows');if(document.querySelector('.fx-art-aura'))throw Error('Animated aura ignores reduced motion');`);
 await screenshot('growth-mobile-reduced');
 await evalJS('SpireFX.configure({intensity:0,reduced:false});SpireFX.clear();if(SpireFX.activeParticles)throw Error("Effects Off ignored")');

 if(errors.length)throw Error(errors.join('\n'));console.log('Playable review passed: card proportions, combat/ability choices, information control, arrows, confirmation, Escape, response timing, real resolution, invalid targets, buff inspection and mobile layout, spell trails, crackle, scorch cleanup, meteor showers, eight non-fire families, pending charges, real resolutions, cleanup, reduced motion and Effects Off.');
}finally{try{await call('Browser.close')}catch{}ws.close()}
