// Isolated real-browser checks for state races, decisions, routes, and earned loot.
import fs from 'node:fs/promises';
const [base,port,fixturePath]=process.argv.slice(2);
const fixtures=JSON.parse(await fs.readFile(fixturePath,'utf8'));
const target=await(await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(base)}`,{method:'PUT'})).json();
const ws=new WebSocket(target.webSocketDebuggerUrl.replace('localhost','127.0.0.1'));
await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});
let serial=0,checkNumber=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)});
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++serial,timer=setTimeout(()=>{pending.delete(id);reject(Error('Debugger timeout: '+method))},15000);pending.set(id,{resolve:r=>{clearTimeout(timer);resolve(r)},reject:e=>{clearTimeout(timer);reject(e)}});ws.send(JSON.stringify({id,method,params}))})}
async function evaluate(code){const step=++checkNumber;let r;try{r=await call('Runtime.evaluate',{expression:`(async()=>{${code}})()`,awaitPromise:true,returnByValue:true,userGesture:true})}catch(e){throw Error('QOL evaluation '+step+': '+e.message)}if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function wait(expression){for(let n=0;n<120;n++){if(await evaluate(`return typeof state!=='undefined'&&(${expression})`))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+expression)}
async function shot(name){await evaluate(`await Promise.all([...document.images].filter(i=>i.getClientRects().length).map(i=>{i.loading='eager';return i.decode().catch(()=>{})}))`);const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await fs.writeFile(`artifacts/tactical-qol-${name}.png`,Buffer.from(r.data,'base64'))}
try{
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1500,height:1100,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:base});await wait(`!!document.querySelector('[data-action="createSolo"]')`);
 await evaluate(`globalThis.fixtures=${JSON.stringify(fixtures)};seat(fixtures.build)`);await wait(`state?.stage==='build'&&!busy`);
 await evaluate(`if(state.campaign_map.nodes.length!==10||state.campaign_map.nodes.some(n=>n.modifiers.length))throw Error('Custom map count');if(document.querySelectorAll('.map-node:not(:disabled)').length!==3)throw Error('Reachable routes missing');const nodes=[...document.querySelectorAll('.map-node:not(:disabled)')];nodes[1].click()`);await wait(`!busy&&state.selected_node===state.campaign_map.reachable[1]`);
 await evaluate(`const input=document.querySelector('[data-qol-pref="deck:search"]');input.value='recruit';input.dispatchEvent(new Event('input',{bubbles:true}));if([...document.querySelectorAll('[data-collection="deck"]>.card:not([hidden])')].some(c=>!c.textContent.toLowerCase().includes('recruit')))throw Error('Search did not filter');input.focus();input.setSelectionRange(2,4);document.querySelector('.mana-curve').open=true;const feedback=document.querySelector('#feedback');feedback.value='Keep this unfinished thought';render();if(document.activeElement.dataset.qolPref!=='deck:search'||document.activeElement.selectionStart!==2)throw Error('Search focus lost');if(!document.querySelector('.mana-curve').open||document.querySelector('#feedback').value!=='Keep this unfinished thought')throw Error('Panel/input state lost');document.querySelector('.mana-curve summary').focus();render();if(document.activeElement!==document.querySelector('.mana-curve summary'))throw Error('Disclosure focus lost');delete qolPrefs.deck;qolPrefs.deck={sort:'cost'};render();const costs=[...document.querySelectorAll('[data-collection="deck"]>.card')].map(c=>cardById(c.dataset.artKey).cost);if(costs.some((c,i)=>i&&c<costs[i-1]))throw Error('Cost sort failed');qolPrefs.deck={kind:'creature',cost:'1'};render();if([...document.querySelectorAll('[data-collection="deck"]>.card:not([hidden])')].some(c=>{const x=cardById(c.dataset.artKey);return x.kind!=='creature'||x.cost!==1}))throw Error('Type/cost filter failed');if(!document.querySelector('.curve-bars'))throw Error('Missing mana curve');delete qolPrefs.deck;render();`);
 await evaluate(`qolPrefs.equipment={tier:'2',status:'bag'};render();if([...document.querySelectorAll('[data-collection="equipment"]>button:not([hidden])')].some(n=>{const x=state.inventory.find(x=>x.uid===n.dataset.action.split(':')[1]);return x.tier!==2||state.me.equipped.includes(x.uid)}))throw Error('Equipment filters failed');delete qolPrefs.equipment;inventorySelection={kind:'card',id:state.upgrade_previews[0].current.id};render();if(!document.querySelector('.upgrade-preview').textContent.includes('Need 2 more Essence'))throw Error('Missing upgrade shortage');if(!document.querySelector('.inventory-bag .item-tile small')?.textContent.includes('Slot'))throw Error('Missing equipped slot');`);
 await evaluate(`globalThis.realFetch=fetch;swap=state.me.deck[0];fetch=async()=>{throw Error('Simulated offline')};await act('deck',{deck:state.me.deck});if(!swap)throw Error('Failed exchange discarded selection');fetch=realFetch;swap=null;window.confirm=()=>false;const currency=state.currency;await act('buy',{index:0});if(state.currency!==currency)throw Error('Cancelled purchase spent currency');window.confirm=()=>true;await act('buy',{index:0});if(state.currency!==currency-1)throw Error('Confirmed purchase failed');fetch=async()=>{throw Error('Simulated offline')};await poll();if(!connection.textContent.includes('Connection interrupted'))throw Error('Missing recovery status');fetch=realFetch;await poll();if(connection.textContent.includes('interrupted'))throw Error('Recovery indicator stuck');`);
 await evaluate(`const same=structuredClone(state),realRequest=request;globalThis.waiters=[];request=async()=>await new Promise(r=>waiters.push(r));const p1=poll(),p2=poll();waiters[1]({...structuredClone(same),currency:222});await p2;waiters[0]({...structuredClone(same),currency:111});await p1;if(state.currency!==222)throw Error('Older poll overwrote latest');request=realRequest;await poll();Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{globalThis.copiedCode=value}}});document.querySelector('[data-action="copyRoom"]').click();await new Promise(r=>setTimeout(r,10));if(copiedCode!==credentials.code)throw Error('Copy code failed');`);
 await shot('build');
 await evaluate(`SpireFX.configure({fast:true,reduced:false,intensity:1});globalThis.lootId=state.treasures[0].id;globalThis.itemCount=state.inventory.length;globalThis.lootCurrency=state.currency;openTreasure(lootId);if(document.querySelectorAll('.loot-strip').length!==state.treasures[0].items.length)throw Error('Missing item reels');for(const [i,n] of [...document.querySelectorAll('.loot-strip')].entries())if(n.children[21].querySelector('b:last-child').textContent.trim()!==state.treasures[0].items[i].name)throw Error('Reel lands on wrong item');`);
 await shot('treasure-spin');await wait(`!!document.querySelector('[data-loot-close]')&&!busy`);
 await evaluate(`if(state.inventory.length!==itemCount||state.currency!==lootCurrency)throw Error('Reveal re-awarded loot');cancelTreasure();SpireFX.configure({reduced:true});openTreasure(lootId);if(document.querySelector('.loot-strip'))throw Error('Reduced motion has spinning reel');if(document.querySelectorAll('.loot-item').length!==state.treasures[0].items.length)throw Error('Missing reduced reward results');const d=treasureDialog;d.dispatchEvent(new Event('cancel',{cancelable:true}));if(d.open)throw Error('Escape did not close revealed treasure');`);await shot('treasure-reduced');
 await evaluate(`cancelTreasure();SpireFX.configure({reduced:false});const realRequest=request,saved=structuredClone(state);globalThis.releaseOld=null;request=async()=>await new Promise(r=>releaseOld=r);globalThis.oldPoll=poll();request=realRequest;seat(fixtures.battle);globalThis.oldBuild=saved;`);await wait(`state?.stage==='battle'`);
 await evaluate(`releaseOld(oldBuild);await oldPoll;if(state.stage!=='battle')throw Error('Old room response changed current room');if(state.battle.players[1].hand.length)throw Error('Hidden hand leaked');const grave=document.querySelector('.own-player [data-panel="grave"]');grave.open=true;render();if(!document.querySelector('.own-player [data-panel="grave"]').open)throw Error('Graveyard closed');const exile=document.querySelector('.player:not(.own-player) [data-panel="exile"]');exile.open=true;if(!exile.querySelector('.card'))throw Error('No public exile cards');exile.querySelector('.art-inspect').click();if(!document.querySelector('#artInspector').open)throw Error('Exile inspection unavailable');document.querySelector('#artInspector').close();`);
 await evaluate(`const card=state.battle.players[0].hand.find(c=>c.id==='u_return');selectCast(card.uid);const target=document.querySelector('.player:not(.own-player) .board [data-action^="target:"]');target.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,pointerType:'mouse'}));await new Promise(r=>setTimeout(r,500));if(document.querySelector('.card-hover-preview'))throw Error('Inspection obscured targeting');if(!document.querySelector('.qol-tooltip')?.textContent.includes('3 mana'))throw Error('Ward hover cost missing');target.click();if(!document.querySelector('.target-cost').textContent.includes('Ward'))throw Error('Touch target cost missing');document.querySelector('[data-action="cancel"]').click();`);
 await evaluate(`home=true;globalThis.savedBattle=structuredClone(state);state.battle.phase='combat';state.battle.active=state.battle.priority=0;home=false;render();const uid=state.battle.players[0].board[0].uid;attackChoices[uid]=1;render();if(!document.querySelector('.combat-summary').textContent.includes('1 attackers'))throw Error('Attack count missing');fetch=async()=>{throw Error('Rejected attack')};await act('attack',{attacks:[{uid,defender:1}]});fetch=realFetch;if(attackChoices[uid]!==1)throw Error('Failed confirmation discarded attacks');document.querySelector('[data-action="combatClearAll"]').click();if(Object.keys(attackChoices).length)throw Error('Clear attacks failed');state.battle.phase='blocks';blockChoices[uid]=state.battle.players[1].board[0].uid;render();if(!document.querySelector('.combat-summary').textContent.includes('1 blockers'))throw Error('Block count missing');document.querySelector('[data-action="combatClearAll"]').click();if(Object.keys(blockChoices).length)throw Error('Clear blocks failed');state=savedBattle;state.battle.phase='combat';state.battle.players[0].board[0].sick=true;render();const n=document.querySelector('.own-player .board .card');n.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,pointerType:'mouse'}));await new Promise(r=>setTimeout(r,450));if(!document.querySelector('.qol-tooltip')?.textContent.includes('cannot attack')||document.querySelector('.card-hover-preview'))throw Error('Missing brief creature reason');home=true;`);
 await evaluate(`home=false;state.battle.encounter.terrain='field';render();if(!getComputedStyle(document.querySelector('.temple-table')).backgroundImage.includes('battlefield-field'))throw Error('Field background missing');const a=new Image();a.src='/battlefield-field.png';await a.decode();const b=new Image();b.src='/battlefield-town.png';await b.decode();if(!a.naturalWidth||!b.naturalWidth)throw Error('Background asset missing');home=true;`);await shot('field');await evaluate(`home=false;state.battle.encounter.terrain='town';render();home=true;`);await shot('town');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await evaluate(`home=false;state.battle.encounter.terrain='town';render();home=true;if(document.documentElement.scrollWidth>innerWidth+1)throw Error('Mobile battlefield overflow');if(getComputedStyle(document.querySelector('.decision-panel')).position!=='fixed')throw Error('Mobile decisions changed');`);await shot('town-mobile');
 await evaluate(`home=false;document.querySelector('.own-orb').scrollIntoView({block:'center'});const previous=structuredClone(state.battle);state.battle.players[0].hp+=2;SpireFX.presentState(previous,state.battle);if(!document.querySelector('.fx-state-number'))throw Error('Missing healing feedback');SpireFX.clear();if(document.querySelector('.fx-state-number'))throw Error('Orphan animation after clear');if(document.querySelector('.fx-environment')&&!document.querySelector('.fx-environment').hidden)throw Error('Ambience persists outside battle');home=true;`);
 await evaluate(`seat(fixtures.build)`);await wait(`state?.stage==='build'`);
 await evaluate(`if(qolPrefs.deck?.sort==='cost')throw Error('Fixture room filter unexpectedly retained deleted preference');qolPrefs.deck={search:'recruit'};saveQolPrefs();render();`);
 await call('Page.reload');await wait(`state?.stage==='build'&&document.querySelector('[data-qol-pref="deck:search"]')?.value==='recruit'`);
 await evaluate(`if(document.documentElement.scrollWidth>innerWidth+1)throw Error('Mobile build overflow');`);await shot('map-mobile');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('QOL browser passed: filters, focus/panels/drafts, routes, failed actions, spending cancellation, polling races/recovery, public zones, targeting costs, combat reset/counts, loot persistence/reduced motion, backgrounds and mobile layout.');
}finally{try{await call('Browser.close')}catch{}ws.close()}
