const manaNames={W:'White',U:'Blue',B:'Black',R:'Red',G:'Green',C:'Generic'};
const manaShapes={W:'<circle cx="12" cy="12" r="5"/><path d="M11 1h2v4h-2zM11 19h2v4h-2zM1 11h4v2H1zM19 11h4v2h-4zM3 4l2-1 3 3-2 2zM17 17l2-2 3 4-2 1zM17 6l3-3 2 1-3 4zM3 20l-1-2 4-3 2 2z"/>',U:'<path d="M12 2S5 10 5 15a7 7 0 0 0 14 0c0-5-7-13-7-13z"/>',B:'<path d="M5 10a7 7 0 0 1 14 0v6l-3 1v4H8v-4l-3-1z"/><circle cx="9" cy="11" r="2" fill="var(--pip)"/><circle cx="15" cy="11" r="2" fill="var(--pip)"/>',R:'<path d="M13 2c3 7-3 7 1 11l3-5c8 11 0 15-5 15S1 18 5 11l3 3C6 8 12 8 13 2z"/>',G:'<path d="M12 1 5 9h3l-5 7h7v6h4v-6h7l-5-7h3z"/>'};
function manaPip(color,value=''){return `<span class="mana-pip ${color}" title="${manaNames[color]}${value!==''?' '+value:''}" aria-label="${manaNames[color]}${value!==''?' '+value:''}">${value!==''?value:`<svg viewBox="0 0 24 24" aria-hidden="true">${manaShapes[color]||''}</svg>`}</span>`}
function cardHTML(c,action='',extra='',target=false){
    const artKey=c.id==='commander'?'commander_'+state.battle.players[c.owner].commander:c.token?'token_recruit':c.id;
    inspectionCards.set(artKey,c);
    const attack=c.shown_attack??c.attack,health=(c.shown_health??c.health)-(c.damage||0);
    const identity=c.id==='commander'?(state.commanders?.find(x=>x.id===state.battle.players[c.owner].commander)?.colors||['W','U']):[c.color||'C'];
    const tones={W:'#eee0b4',U:'#70c5ef',B:'#af8ac5',R:'#ec8057',G:'#8bc88c',C:'#8f7353'};
    const dual=identity.length===2;
    return `<div ${c.uid?`data-uid="${esc(c.uid)}"`:""} data-art-key="${esc(artKey)}" class="card ${esc(c.color||'C')} ${c.id==='commander'?'commander':''} ${c.tapped?'tapped':''} ${target?'target':''} ${dual?'dual':''}" ${dual?`style="--left:${tones[identity[0]]};--right:${tones[identity[1]]}"`:''} ${action?`data-action="${action}" tabindex="0" role="button"`:''}><div class="card-title"><strong>${esc(c.name)}</strong><span class="mana-cost">${manaCost(c)}</span></div><img class="illustration" style="object-position:center ${artKey==='r_wipe'?'75%':'25%'}" loading="lazy" alt="${esc(c.name)}" src="${window.cardArtURL?window.cardArtURL(artKey):'/art/'+esc(artKey)+'?v=anime-2'}"><div class="card-type">${c.id==='commander'?'Commander · ':''}${esc(c.kind)}</div><div class="card-rules"><small>${esc(c.text)}</small><div>${(c.keywords||[]).map(k=>`<span class="tag" title="${esc(state.battle?.keywords[k]||k)}">${esc(k)}</span>`).join('')}</div></div>${c.kind==='creature'?`<div class="stats"><span>${attack} / ${health}</span><span class="card-state">${c.damage?c.damage+' damage ':''}${c.tapped?'Exhausted ':''}${c.sick&&c.shown_attack!==undefined?'New':''}</span></div>`:''}${extra?`<div class="card-controls">${extra}</div>`:''}<button class="art-inspect" data-action="inspect:${esc(artKey)}" aria-label="Inspect ${esc(c.name)} artwork and rules">Inspect</button></div>`
}
