/* Small controls and presentation additions within the established game UI. */
let qolRoom='', qolPrefs={}, qolTooltip, treasureDialog, treasureTimer, treasureSerial=0;
function loadQolRoom(){
 const key=credentials?.code||'';
 if(qolRoom===key)return;
 qolRoom=key;try{qolPrefs=JSON.parse(sessionStorage.getItem('spire-qol:'+key)||'{}')}catch{qolPrefs={}}
 inventorySelection=null;focusedOpponent=null;lastLessonStep=null;cancelTreasure();document.querySelector('#artInspector')?.close();
}
function saveQolPrefs(){try{sessionStorage.setItem('spire-qol:'+qolRoom,JSON.stringify(qolPrefs))}catch{}}
function panelKey(n){return (n.closest('[data-player]')?.dataset.player||'')+':'+(n.dataset.panel||n.querySelector(':scope > summary')?.textContent.replace(/\d+/g,'').trim())}
function snapshotQol(){
 const active=document.activeElement;
 return {room:app.dataset.room,stage:app.dataset.stage, panels:new Map([...app.querySelectorAll('details')].map(n=>[panelKey(n),n.open])),
  inputs:new Map([...app.querySelectorAll('input[type="text"],input:not([type]),textarea')].filter(n=>n.id).map(n=>[n.id,n.value])),
  focus:active&&app.contains(active)?{id:active.id,action:active.dataset.action,pref:active.dataset.qolPref,panel:active.matches('summary')?panelKey(active.closest('details')):null,start:active.selectionStart,end:active.selectionEnd}:null,
  scroll:new Map([...app.querySelectorAll('.zone-cards,.log,.cardgrid')].map((n,i)=>[i,[n.scrollLeft,n.scrollTop]]))};
}
function restoreQol(s){
 if(s.room!==credentials?.code||s.stage!==state.stage)return;
 for(const n of app.querySelectorAll('details'))if(s.panels.has(panelKey(n)))n.open=s.panels.get(panelKey(n));
 for(const [id,value] of s.inputs){const n=document.getElementById(id);if(n&&app.contains(n))n.value=value}
 const f=s.focus;if(f){const n=f.id?document.getElementById(f.id):f.pref?app.querySelector(`[data-qol-pref="${CSS.escape(f.pref)}"]`):f.action?app.querySelector(`[data-action="${CSS.escape(f.action)}"]`):f.panel?[...app.querySelectorAll('details')].find(n=>panelKey(n)===f.panel)?.querySelector(':scope > summary'):null;if(n&&!n.disabled){n.focus({preventScroll:true});if(f.start!=null&&n.setSelectionRange)try{n.setSelectionRange(f.start,f.end)}catch{}}}
 [...app.querySelectorAll('.zone-cards,.log,.cardgrid')].forEach((n,i)=>{const p=s.scroll.get(i);if(p){n.scrollLeft=p[0];n.scrollTop=p[1]}});
}
function collectionTools(key,cards=true){
 const p=qolPrefs[key]||{};
 const options=(values,value)=>values.map(([id,label])=>`<option value="${id}" ${String(value||'')===id?'selected':''}>${label}</option>`).join('');
 return `<div class="qol-tools" role="group" aria-label="${esc(key)} search and filters"><label>Search <input type="search" data-qol-pref="${key}:search" value="${esc(p.search||'')}" placeholder="Name or rules"></label>${cards?`<label>Color <select data-qol-pref="${key}:color">${options([['','All'],...Object.entries(colors)],p.color)}</select></label><label>Type <select data-qol-pref="${key}:kind">${options([['','All'],['creature','Creature'],['spell','Spell'],['response','Response'],['engine','Engine'],['equipment','Equipment'],['enchantment','Enchantment']],p.kind)}</select></label><label>Cost <select data-qol-pref="${key}:cost">${options([['','All'],['0','0'],['1','1'],['2','2'],['3','3'],['4','4'],['5','5'],['6','6+']],p.cost)}</select></label><label>Sort <select data-qol-pref="${key}:sort">${options([['','Original'],['name','Name'],['cost','Cost'],['copies','Copies']],p.sort)}</select></label>`:key==='equipment'?`<label>Status <select data-qol-pref="${key}:status">${options([['','All'],['equipped','Equipped'],['bag','Unequipped']],p.status)}</select></label><label>Tier <select data-qol-pref="${key}:tier">${options([['','All'],['0','Base'],['1','+1'],['2','+2']],p.tier)}</select></label>`:''}<button data-action="resetFilters:${key}">Reset</button><small data-filter-count="${key}" aria-live="polite"></small></div>`;
}
function filterCollections(){
 for(const root of app.querySelectorAll('[data-collection]')){
  const key=root.dataset.collection,p=qolPrefs[key]||{},nodes=[...root.children].filter(n=>n.matches('.card,button'));
  const spec=n=>key==='equipment'?state.inventory.find(x=>x.uid===n.dataset.action?.split(':')[1]):key==='upgrades'?state.upgrade_previews.find(x=>x.current.id===n.dataset.action?.split(':')[1])?.current:cardById(n.dataset.artKey);
  for(const n of nodes){const c=spec(n);if(!c)continue;const equipped=state.me.equipped?.includes(c.uid)||state.me.deck?.includes('gear:'+c.uid),kind=['foundry','relay','anthem'].includes(c.effect)?'engine':c.kind;n.hidden=!!((p.search&&!`${c.name} ${c.text}`.toLowerCase().includes(p.search.toLowerCase()))||(p.color&&c.color!==p.color)||(p.kind&&kind!==p.kind)||(p.cost&&(p.cost==='6'?c.cost<6:c.cost!==Number(p.cost)))||(p.status&&(p.status==='equipped'?!equipped:equipped))||(p.tier&&c.tier!==Number(p.tier)))}
  const original=new Map(nodes.map((n,i)=>[n,n.dataset.originalOrder??(n.dataset.originalOrder=i)]));
  nodes.sort((a,b)=>{const ca=spec(a),cb=spec(b);if(!ca||!cb)return 0;if(p.sort==='name')return ca.name.localeCompare(cb.name);if(p.sort==='cost')return ca.cost-cb.cost||ca.name.localeCompare(cb.name);if(p.sort==='copies'){const count=id=>key==='deck'?state.me.deck.filter(x=>x===id).length:state.me.owned.filter(x=>x===id).length-state.me.deck.filter(x=>x===id).length;return count(cb.id)-count(ca.id)||ca.name.localeCompare(cb.name)}return Number(original.get(a))-Number(original.get(b))});nodes.forEach(n=>root.append(n));
  const count=app.querySelector(`[data-filter-count="${key}"]`);if(count)count.textContent=`${nodes.filter(n=>!n.hidden).length} / ${nodes.length} shown`;
 }
}
function cardOwnership(id){const owned=state.me.owned.filter(x=>x===id).length,deck=state.me.deck.filter(x=>x===id).length;return `${owned} owned · ${deck} in deck`}
function exchangeReason(id){if(!swap)return '';if(state.me.ready)return 'Build already confirmed.';if(!legal(id))return 'Outside your colors.';const deck=counts(state.me.deck);const identity=cardById(id).base_design||id,total=state.me.deck.filter(ref=>(cardById(ref).base_design||ref)===identity).length-((cardById(swap).base_design||swap)===identity?1:0);if(!state.basics.includes(identity)&&total>=2)return 'Two-copy limit.';return ''}
function curveHTML(){const bins=Array(7).fill(0);for(const id of state.me.deck)bins[Math.min(6,cardById(id).cost)]++;return `<details class="panel mana-curve" data-panel="curve"><summary>Mana curve · ${state.me.deck.length} cards</summary><div class="curve-bars">${bins.map((n,i)=>`<div><b>${n}</b><span style="height:${8+n*5}px"></span><small>${i===6?'6+':i} mana</small></div>`).join('')}</div></details>`}
function mapHTML(){const map=state.campaign_map;if(!map)return '';const depth=state.encounter.battle-1;return `<section class="panel campaign-map"><h3>Act ${map.act} · Choose your path →</h3><p>${esc(state.difficulty)} · Left to right · Shops and preparation stay available between battles.</p><div class="map-scroll"><div class="map-path"><div class="map-start">Start →</div>${[0,1,2,3].map(column=>`<section class="map-column" aria-label="Battle ${column+1}">${map.nodes.filter(n=>n.column===column).map(n=>{const reachable=map.reachable.includes(n.id),chosen=n.id===state.selected_node;return `<button class="map-node ${chosen?'selected':''} ${n.completed?'completed':''}" data-action="route:${n.id}" ${!reachable||state.stage!=='build'?'disabled':''} aria-pressed="${chosen}"><b>${n.completed?'✓ ':''}${n.kind}</b><span>${n.terrain==='town'?'Town street':n.terrain==='field'?'Open field':'Temple'}</span><small>${n.modifiers.map(id=>state.modifiers[id].name).join(' · ')||'No challenges'}</small><strong>${n.essence} Essence on victory</strong>${chosen?'<small>Selected route</small>':''}</button>`}).join('')}</section>${column<3?'<div class="map-service"><span>→</span><b>Shop</b><small>Prepare</small><span>→</span></div>':''}`).join('')}</div></div><p class="muted">Each route connects to the same or neighboring lane, then the boss. Marked nodes contain 1–3 challenges; bonus Essence caps at +4.</p>${state.encounter.modifiers.map(id=>`<p><b>${esc(state.modifiers[id].name)}</b>: ${esc(state.modifiers[id].text)} (+${state.modifiers[id].essence} Essence)</p>`).join('')}</section>`}
function drawMapEdges(){
 const path=document.querySelector('.map-path');if(!path||!state.campaign_map)return;
 let svg=path.querySelector('.route-lines');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('route-lines');svg.setAttribute('aria-hidden','true');path.prepend(svg)}
 const r=path.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);
 const point=id=>{const n=path.querySelector(`[data-action="${CSS.escape('route:'+id)}"]`);return n?.getBoundingClientRect()};
 svg.innerHTML=state.campaign_map.nodes.flatMap(n=>n.next.map(id=>{const a=point(n.id),b=point(id);if(!a||!b)return '';const x=a.right-r.left,y=a.top+a.height/2-r.top,xx=b.left-r.left,yy=b.top+b.height/2-r.top;return `<path d="M${x},${y} C${(x+xx)/2},${y} ${(x+xx)/2},${yy} ${xx},${yy}" fill="none" stroke="${n.completed?'#ffe3a0':'#91a899'}" stroke-width="${n.completed?3:1.5}"/>`})).join('');
}
function treasureHTML(){const loot=state.treasures||[];if(!loot.length)return '';return `<section class="panel treasure-rewards"><h3>Earned treasures</h3><p>Ordinary victory: 25% chest chance · Boss: guaranteed. Each chest: 1–3 items and 1–3 currency, equal chances. Each item: 75% base · 20% +1 · 5% +2.</p>${[...loot.filter(t=>!t.revealed),...loot.filter(t=>t.revealed).slice(-4)].map(t=>`<article><b>Treasure · ${t.items.length} items · ${t.currency} currency</b> ${button(t.revealed?'View rewards':'Open treasure','treasure:'+t.id,false,'primary')}<small>Already awarded and saved. Opening is free.</small></article>`).join('')}</section>`}
function showTip(text,target){if(!text){qolTooltip?.remove();qolTooltip=null;return}if(!qolTooltip){qolTooltip=document.createElement('div');qolTooltip.className='qol-tooltip';qolTooltip.role='tooltip';document.body.append(qolTooltip)}qolTooltip.textContent=text;const r=target.getBoundingClientRect();qolTooltip.style.left=Math.max(8,Math.min(r.left,innerWidth-290))+'px';qolTooltip.style.top=Math.max(8,Math.min(r.bottom+6,innerHeight-90))+'px'}
function targetCostHint(target){
 if(!selected)return '';
 const b=state.battle,me=b.players[state.me.seat],source=[...me.hand,...me.board,...me.engines,...(me.gear||[]),...(me.pouch||[])].find(c=>c.uid===selected.uid);
 const spec=source?.abilities?.find(a=>a.index===selected.ability);
 let mana=selected.action==='cast'?(source?.cost||0):spec?.cost??(selected.action==='equip_gear'?source?.equip_cost:selected.action==='consume'?source?.cost:source?.effect==='mana'?0:source?.commander?2:1);
 const victim=b.players.flatMap(p=>[...p.board,...(p.gear||[])]).find(c=>c.uid===target),ward=victim&&victim.owner!==me.id&&(victim.ward_cost??(victim.keywords.includes('Ward')?1:0));if(ward)mana++;
 const extra=[];const pips=['cast','consume'].includes(selected.action)?source?.pips:spec?.pips;for(const [color,count] of Object.entries(pips||{}))extra.push(`${count} ${colors[color]}`);if(ward)extra.push('includes 1 Ward');const wardPayments=[...(victim?.ward_payments||[]),...(victim?.ward?[victim.ward]:[])];if(victim?.owner!==me.id&&wardPayments.length)extra.push('Ward '+wardPayments.map(n=>'{'+n+'}').join(' + ')+' on resolution');if(selected.action==='consume')extra.push('item permanently spent');if(spec?.health_cost)extra.push(`${spec.health_cost} health`);if(spec?.discard||selected.costField==='discard'||source?.id==='r_loot')extra.push('discard a card');if(spec?.sacrifice||selected.costField==='sacrifice')extra.push('sacrifice a creature');if(!spec&&['destroy','bargain'].includes(source?.effect))extra.push('2 health');
 return `${mana} mana${extra.length?' · '+extra.join(' · '):''}`;
}
function creatureReason(c){const b=state.battle;if(c.owner!==state.me.seat)return '';if(b.priority!==state.me.seat)return 'Wait for your priority.';if(c.tapped)return 'Creature is exhausted.';if(b.phase==='combat'){if(c.sick&&!c.keywords.includes('Haste'))return 'New creature: cannot attack yet.';if(b.stack.length)return 'Resolve pending actions first.';return ''}if(b.phase==='blocks')return '';return abilityKind(c)?abilityReason(c):''}
function abilityReason(c){const b=state.battle,me=b.players[state.me.seat];if(b.priority!==me.id)return 'Wait for your priority.';if(b.choice||['opening','grow'].includes(b.phase))return 'Finish the current decision.';if(c.tapped)return 'Creature is exhausted.';if(c.sick&&!c.keywords.includes('Haste'))return 'New creature: ability unavailable.';if(!canPay(c.effect==='mana'?0:c.commander?2:1,{},me))return 'Not enough mana.';if(c.effect==='sacrifice'&&me.board.length<2)return 'Need another creature.';if(c.effect==='loot'&&!me.hand.length)return 'Need a card to discard.';return ''}
function confirmSpending(action,data){
 if(action==='buy_gem')return confirm('Unlock '+data.design+' gem for 2 currency?');if(action==='buy_consumable')return confirm('Buy '+state.consumable_catalog.find(c=>c.id===data.design).name+' for 1 currency?');if(action==='upgrade_gem')return confirm('Upgrade '+data.gem+' for '+(state.me.gem_unlocks[data.gem]===0?3:6)+' Essence?');
 let description='';if(action==='buy')description=`Buy ${cardById(state.shop[data.index]).name} for 1 currency?`;if(action==='buy_item')description=`Buy ${equipmentSpec(state.gear_shop[data.index]).name} for 2 currency?`;if(action==='refresh')description='Replace the shop offers for 1 currency?';if(action==='upgrade_card'){const p=state.upgrade_previews.find(p=>p.current.id===data.design);description=`Upgrade ${p.current.name} for ${p.cost} Essence?`}if(action==='upgrade_item'){const x=state.inventory.find(x=>x.uid===data.uid);description=`Upgrade ${x.name} for ${x.tier===0?3:6} Essence?`}return !description||confirm(description);
}
function cancelTreasure(){qolTooltip?.remove();qolTooltip=null;treasureSerial++;clearTimeout(treasureTimer);treasureDialog?.close();treasureDialog?.remove();treasureDialog=null}
function openTreasure(id){
 const t=state.treasures.find(t=>t.id===id);if(!t)return;cancelTreasure();const token=treasureSerial,room=credentials.code;let finished=false;
 const d=document.createElement('dialog');treasureDialog=d;d.className='treasure-dialog';d.innerHTML=`<header><h2>Treasure found</h2><button data-loot-skip>Skip reveal</button></header><p>${t.currency} currency · ${t.items.length} awarded items</p><p>75% base · 20% +1 · 5% +2 per item</p><div class="loot-result" aria-live="polite"></div>`;document.body.append(d);d.showModal();
 const finish=()=>{if(finished||token!==treasureSerial||credentials.code!==room)return;finished=true;clearTimeout(treasureTimer);d.querySelector('.loot-result').innerHTML=`<div class="loot-items">${t.items.map(x=>`<article class="loot-item tier-${x.tier}">${itemArt(x)}<h3>${esc(x.name)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div><p>Added to your inventory · +${t.currency} currency</p><button data-loot-close>Continue</button>`;d.querySelector('[data-loot-skip]').hidden=true;d.querySelector('[data-loot-close]').onclick=()=>cancelTreasure();if(!t.revealed){SpireFX.playCue?.(t.items.some(x=>x.tier===2)?'rare':'treasure');act('treasure_revealed',{id})}};
 d.qolFinish=finish;d.querySelector('[data-loot-skip]').onclick=finish;d.addEventListener('cancel',e=>{e.preventDefault();if(finished)cancelTreasure();else finish()});
 if(t.revealed||SpireFX.settings.reduced||SpireFX.settings.intensity===0){finish();return}
 const catalog=state.equipment_catalog;d.querySelector('.loot-result').innerHTML=t.items.map((item,j)=>`<div class="loot-window"><div class="loot-strip" data-reel="${j}">${Array.from({length:24},(_,i)=>{const x=i===21?item:catalog[(i+j*3)%catalog.length];return `<div class="loot-cell tier-${x.tier}">${itemArt(x)}<b>${esc(x.name)}</b></div>`}).join('')}</div><span class="loot-pointer">◆</span></div>`).join('');
 requestAnimationFrame(()=>{if(token!==treasureSerial)return;d.querySelectorAll('.loot-strip').forEach(n=>n.animate([{transform:`translateX(${n.parentElement.clientWidth/2-70}px)`},{transform:`translateX(${n.parentElement.clientWidth/2-3010}px)`}],{duration:SpireFX.settings.fast?900:3900,easing:'cubic-bezier(.12,.6,.12,1)',fill:'forwards'}))});
 const started=performance.now(),duration=SpireFX.settings.fast?900:4000;const tick=()=>{if(token!==treasureSerial)return;const elapsed=performance.now()-started;if(elapsed>=duration){finish();return}SpireFX.playCue?.('tick');treasureTimer=setTimeout(tick,65+elapsed/duration*260)};tick();
}
function decorateQol(){filterCollections();showTip('',app);requestAnimationFrame(drawMapEdges);for(const card of app.querySelectorAll('.board .card')){const uid=card.dataset.uid,c=state.battle?.players.flatMap(p=>p.board).find(c=>c.uid===uid);if(c)card.dataset.reason=creatureReason(c)}}
addEventListener('resize',()=>requestAnimationFrame(drawMapEdges));
document.addEventListener('toggle',e=>{if(e.target.matches?.('.zone-drawer')&&e.target.open)document.querySelectorAll('.zone-drawer[open]').forEach(drawer=>{if(drawer!==e.target)drawer.open=false})},true);
document.addEventListener('input',e=>{const key=e.target.dataset.qolPref;if(!key)return;const [group,name]=key.split(':');(qolPrefs[group]??={})[name]=e.target.value;saveQolPrefs();filterCollections()});
document.addEventListener('change',e=>{if(e.target.dataset.qolPref)e.target.dispatchEvent(new Event('input',{bubbles:true}))});
document.addEventListener('pointerover',e=>{if(!state||home)return;const target=e.target.closest('[data-action^="target:"]');if(selected&&target){showTip(targetCostHint(target.dataset.action.slice(7)),target);return}const ability=e.target.closest('[data-action^="ability:"]'),card=e.target.closest('.board .card'),c=card&&state.battle?.players.flatMap(p=>p.board).find(c=>c.uid===card.dataset.uid);if(combatSelection&&state.battle?.phase==='blocks'&&c?.owner!==state.me.seat){const blocker=state.battle.players[state.me.seat].board.find(c=>c.uid===combatSelection);if(c?.keywords.includes('Flying')&&!blocker?.keywords.some(k=>['Flying','Reach'].includes(k)))showTip('Needs Flying or Reach.',card);return}if(!selected&&ability&&c){showTip(abilityReason(c),ability);return}if(card?.dataset.reason&&!selected)showTip(card.dataset.reason,card)});
document.addEventListener('pointerout',e=>{if(!e.relatedTarget?.closest?.('.card,[data-action^="target:"]'))showTip('',app)});
document.addEventListener('focusin',e=>{const target=e.target.closest('[data-action^="target:"]');if(target&&selected)showTip(targetCostHint(target.dataset.action.slice(7)),target)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')showTip('',app)});
document.addEventListener('spire-effects-change',()=>{if(treasureDialog?.open&&(SpireFX.settings.reduced||SpireFX.settings.intensity===0))treasureDialog.qolFinish?.()});
document.addEventListener('click',e=>{const card=e.target.closest('.board .card');if(card?.dataset.reason&&!selected&&!e.target.closest('.art-inspect,[data-action^="ability:"]'))showTip(card.dataset.reason,card)});
