/* Public rules events drive presentation. No animation changes game state. */
window.SpireFX=(()=>{
 const colors={W:'#ffe8a1',U:'#55c9ff',B:'#ac68e8',R:'#ff7732',G:'#69ec94',C:'#dcc298'};
 const families={damage:'fireball',wipe:'meteor',all_damage:'fireburst',drain_all:'drain',protect:'shield',buff:'growth',team_buff:'rally',draw:'wisdom',filter:'wisdom',bounce:'wave',counter:'counter',exile:'banish',destroy:'shadow',revive:'portal',recall:'portal',ramp:'roots',mana:'roots',tokens:'summon',ready:'wind',fight:'clash',goad:'provocation',anthem:'rally',remove_engine:'shatter',heal:'heal',relay_ready:'wind',sacrifice:'sacrifice',loot:'wisdom',bargain:'sacrifice'};
 let profiles={},canvas,ctx,layer,residueLayer,particles=[],marks=[],frame=0,last=0,seen=0,battleKey='',targeting=null,pointer={x:0,y:0},positions=new Map(),snapshots=new Map(),castOrigins=new Map(),audio,master,crackle,lastImpactSound=0,lastPreviewMeteor=0;
 const settings={sound:true,volume:.3,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,fast:false};
 const stats={casts:0,impacts:0,meteors:0,fizzles:0};
 fetch('/effect-profiles.json').then(r=>r.json()).then(p=>profiles=p).catch(()=>{});
 function setup(){if(canvas)return;layer=document.createElement('div');layer.id='spell-fx-layer';layer.setAttribute('aria-hidden','true');canvas=document.createElement('canvas');layer.append(canvas);document.body.append(layer);residueLayer=document.createElement('div');residueLayer.id='spell-residue-layer';residueLayer.setAttribute('aria-hidden','true');document.body.append(residueLayer);ctx=canvas.getContext('2d');resize()}
 function resize(){if(!canvas)return;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
 function locate(uid,owner){let node;if(uid?.startsWith('p:'))node=document.querySelector(`[data-player="${uid}"] .player-label`)||document.querySelector(`[data-player="${uid}"] .player-summary`);else if(uid)node=document.querySelector(`.hand [data-uid="${CSS.escape(uid)}"]`)||document.querySelector(`.board [data-uid="${CSS.escape(uid)}"]`)||document.querySelector(`[data-action="cast:${CSS.escape(uid)}"]`)||document.querySelector(`[data-action="ability:${CSS.escape(uid)}"]`)||document.querySelector(`[data-stack="${CSS.escape(uid)}"]`);if(node){const r=node.getBoundingClientRect();const p={x:r.left+r.width/2,y:r.top+r.height/2};positions.set(uid,p);return p}return positions.get(uid)||positions.get('p:'+owner)||{x:innerWidth*.5,y:innerHeight*.45}}
 function capture(b){if(!b)return;for(const c of b.players.flatMap(p=>p.board)){const node=document.querySelector(`.board [data-uid="${CSS.escape(c.uid)}"]`);if(node){const r=node.getBoundingClientRect();snapshots.set(c.uid,{node:node.cloneNode(true),x:r.x,y:r.y,width:r.width,height:r.height});if(snapshots.size>64)snapshots.delete(snapshots.keys().next().value)}}for(const a of b.stack||[])locate(a.uid,a.owner);for(const p of b.players){locate('p:'+p.id,p.id);for(const c of [...p.board,...p.hand]){if(c.token){const node=document.querySelector('.board [data-art-key="token_recruit"]');if(node){const r=node.getBoundingClientRect();positions.set(c.uid,{x:r.left+r.width/2,y:r.top+r.height/2});continue}}locate(c.uid,p.id)}}}
 function profile(e){const p=profiles[e.card_id]||{};return {family:e.kind==='creature'?(p.family||'summon'):e.effect==='damage'&&e.color==='B'?'drain':e.effect==='damage'&&e.color==='U'?'wave':e.effect==='damage'&&e.color==='G'?'clash':(families[e.effect]||p.family||'sigil'),color:colors[e.color||p.color]||colors.C,seed:p.seed||1}}
 function wake(){setup();if(!frame){last=performance.now();frame=requestAnimationFrame(draw)}}
 function particle(p){if(particles.length<650)particles.push({...p,born:performance.now()+(p.delay||0)*1000,age:0,life:p.life||.7})}
 function burst(at,color,count=30,shape='spark'){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=25+Math.random()*140;particle({x:at.x,y:at.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,color,size:2+Math.random()*4,shape,life:.35+Math.random()*.65})}wake()}
 function ring(at,color,shape='ring'){particle({x:at.x,y:at.y,vx:0,vy:0,color,size:25,shape,life:settings.fast?.35:.9});wake()}
 function mark(at,color,burnt=false){setup();const n=document.createElement('div');n.className=burnt?'spell-scorch':'spell-residue';n.style.left=at.x+'px';n.style.top=at.y+'px';n.style.setProperty('--fx-color',color);residueLayer.append(n);marks.push(n);if(marks.length>16)marks.shift().remove();setTimeout(()=>{n.remove();marks=marks.filter(x=>x!==n)},3200)}
 function sound(kind){if(!settings.sound||!audio||audio.state!=='running'||document.hidden)return;if(kind==='impact'){const stamp=performance.now();if(stamp-lastImpactSound<65)return;lastImpactSound=stamp}const now=audio.currentTime,gain=audio.createGain();gain.connect(master);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.25,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.55);if(['fire','impact','meteor','shatter'].includes(kind)){const buffer=audio.createBuffer(1,audio.sampleRate*.6,audio.sampleRate);const samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*Math.exp(-i/samples.length*3);const source=audio.createBufferSource(),filter=audio.createBiquadFilter();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=kind==='meteor'?500:1800;source.connect(filter).connect(gain);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect()}}else{const oscillator=audio.createOscillator();oscillator.type=kind==='shadow'?'triangle':'sine';oscillator.frequency.setValueAtTime(kind==='shield'?600:350,now);oscillator.frequency.exponentialRampToValueAtTime(kind==='shield'?900:120,now+.5);oscillator.connect(gain);oscillator.start();oscillator.stop(now+.6);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect()}}}
 function unlock(){if(!settings.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(!master){master=audio.createGain();master.gain.value=settings.volume;master.connect(audio.destination)}if(audio.state==='suspended')audio.resume().then(()=>{if(targeting)startCrackle()}).catch(()=>{});if(targeting)startCrackle()}catch{}}
 function stopCrackle(){if(!crackle)return;const n=crackle;crackle=null;try{n.source.stop()}catch{}n.source.disconnect();n.filter.disconnect();n.gain.disconnect()}
 function startCrackle(){
  if(crackle||!settings.sound||!audio||audio.state!=='running'||targeting?.family!=='fireball')return;
  const buffer=audio.createBuffer(1,audio.sampleRate*4,audio.sampleRate),samples=buffer.getChannelData(0);let brown=0,pop=0;
  for(let i=0;i<samples.length;i++){const noise=Math.random()*2-1;brown=(brown+.035*noise)/1.02;if(Math.random()<1/(audio.sampleRate*.12))pop=.4+Math.random()*.6;pop*=Math.exp(-1/(audio.sampleRate*.012));const fade=Math.min(1,i/(audio.sampleRate*.04),(samples.length-i)/(audio.sampleRate*.04));samples[i]=(brown*.8+noise*.07+noise*pop*.65)*fade}
  const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=buffer;source.loop=true;filter.type='lowpass';filter.frequency.value=2600;gain.gain.value=.45;source.connect(filter).connect(gain).connect(master);source.start();crackle={source,filter,gain};
 }
 function setTarget(card,selection){if(!selection||!['cast','ability'].includes(selection.action)){targeting=null;particles=particles.filter(p=>!p.preview);stopCrackle();return}const ability=card?.abilities?.[selection.ability];const e={card_id:card?.id,effect:ability?.effect||card?.effect,kind:ability?'ability':card?.kind,color:card?.color};targeting={...profile(e),uid:selection.uid,target:selection.target,owner:card?.owner};if(settings.reduced){stopCrackle();return}if(targeting.family==='fireball')startCrackle();else stopCrackle();wake()}
 function projectile(from,to,color,meteor=false,hit,delay=0){const duration=settings.fast?.28:meteor?.6:.65;if(!meteor)stats.lastLaunch={from:{...from},to:{...to}};particle({x:from.x,y:from.y,from,to,color,size:14,shape:meteor?'meteor':'projectile',life:duration,hit,delay});wake()}
 function impact(e,at){const p=profile(e);stats.impacts++;sound(['fireball','meteor','fireburst'].includes(p.family)?'impact':p.family==='shield'?'shield':p.family==='shadow'?'shadow':'magic');switch(p.family){
  case 'meteor':burst(at,'#ff6132',settings.reduced?8:48,'ember');mark(at,p.color,true);break;
  case 'fireball':case 'fireburst':burst(at,'#ff7a2b',settings.reduced?8:48,'ember');ring(at,'#ffb152');mark(at,p.color,true);break;
  case 'heal':ring(at,'#8fffba');burst(at,'#c0ffdb',24,'star');break;
  case 'shield':ring(at,p.color,'shield');burst(at,p.color,20,'star');break;
  case 'growth':case 'roots':burst(at,p.color,32,'leaf');ring(at,p.color,'roots');break;
  case 'wave':case 'wind':ring(at,p.color,'wave');burst(at,p.color,26,'drop');break;
  case 'portal':case 'shadow':case 'banish':case 'sacrifice':case 'drain':ring(at,p.color,'portal');burst(at,p.color,30,'wisp');mark(at,p.color);break;
  case 'counter':case 'shatter':ring(at,p.color,'rune');burst(at,p.color,30,'shard');break;
  case 'wisdom':burst(at,p.color,22,'page');ring(at,p.color,'rune');break;
  case 'clash':burst(at,'#fff0b5',32,'shard');ring(at,p.color);break;
  case 'commander':ring(at,p.color,'crown');burst(at,p.color,40,'star');break;
  default:ring(at,p.color,'rune');burst(at,p.color,22+(p.seed%7),'star');
 }}
 function consume(b,{initial=false,reset=false}={}){if(!b)return;setup();const key=b.players.map(p=>p.commander).join('/')+'|'+b.players.map(p=>p.name).join('/');const events=b.visual_events||[];if(initial||reset||key!==battleKey||(events.at(-1)?.seq||0)<seen){seen=events.at(-1)?.seq||0;battleKey=key;clear();positions.clear();snapshots.clear();castOrigins.clear();capture(b);return}const fresh=events.filter(e=>e.seq>seen);for(const e of fresh){seen=Math.max(seen,e.seq);const p=profile(e),from=castOrigins.get(e.action_uid)||locate(e.source_uid,e.owner),at=locate(e.target||'p:'+e.owner,e.owner);if(e.stage==='cast'){stats.casts++;castOrigins.set(e.action_uid,{...from});if(p.family!=='meteor'){ring(from,p.color,p.family==='shield'?'shield':'rune');burst(from,p.color,settings.reduced?4:18,'star')}sound(p.family==='fireball'?'fire':'magic');continue}castOrigins.delete(e.action_uid);if(e.outcome!=='resolved'){stats.fizzles++;burst(at,'#95a9be',12,'shard');continue}if(p.family==='meteor'){const spots=e.affected_uids?.length?e.affected_uids.map(uid=>locate(uid,e.owner)):b.players.flatMap(p=>p.board.map(c=>locate(c.uid,p.id)));for(let i=0;i<15;i++){const column=i%5,row=Math.floor(i/5);spots.push({x:innerWidth*(.23+column*.12)+(Math.random()-.5)*35,y:innerHeight*(.27+row*.14)+(Math.random()-.5)*30})}for(const [i,end] of spots.slice(0,30).entries()){stats.meteors++;const start={x:end.x-120,y:-40-i*22};let ghost;const uid=e.affected_uids?.[i],snapshot=snapshots.get(uid);if(!settings.managedPresentation&&snapshot&&!b.players.some(p=>p.board.some(c=>c.uid===uid))&&!settings.reduced){const cardGhost=snapshot.node;cardGhost.removeAttribute('data-uid');cardGhost.querySelectorAll('button,select').forEach(n=>n.remove());Object.assign(cardGhost.style,{width:'100%',height:'100%',position:'relative',transform:'none'});ghost=document.createElement('div');ghost.className='board spell-departing spell-ghost-slot';ghost.append(cardGhost);Object.assign(ghost.style,{position:'fixed',left:snapshot.x+'px',top:snapshot.y+'px',width:snapshot.width+'px',height:snapshot.height+'px',transform:'none',pointerEvents:'none'});residueLayer.append(ghost)}const hit=()=>{impact(e,end);if(ghost){ghost.classList.add('spell-burnout');setTimeout(()=>ghost.remove(),450)}};if(settings.reduced)hit();else projectile(start,end,p.color,true,hit,(i%7)*.06)}sound('meteor')}else if(e.effect==='team_buff'||e.effect==='goad'||e.effect==='anthem'){const players=e.effect==='team_buff'?b.players.filter(p=>p.id===e.owner):b.players;for(const p of players)for(const c of p.board)impact(e,locate(c.uid,p.id))}else if(p.family==='fireball'&&!settings.reduced){projectile(from,at,p.color,false,()=>impact(e,at))}else impact(e,at)}capture(b)}
 function previewMeteor(now){
  if(settings.reduced||now-lastPreviewMeteor<170)return;
  lastPreviewMeteor=now;
  const to={x:innerWidth*(.23+Math.random()*.55),y:innerHeight*(.27+Math.random()*.32)},from={x:to.x-160,y:-45};
  particle({x:from.x,y:from.y,from,to,color:'#ff6132',size:12,shape:'meteor',life:1.05,preview:true});
 }
 function flameHalo(center,now,scale=1){
  ctx.save();ctx.translate(center.x,center.y);ctx.scale(scale,scale);ctx.globalCompositeOperation='source-over';
  const glow=ctx.createRadialGradient(0,0,17,0,0,58);glow.addColorStop(0,'transparent');glow.addColorStop(.4,'#c7191222');glow.addColorStop(.75,'#f72a172b');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(-62,-72,124,124);
  for(let i=0;i<16;i++){
   const phase=now*.004+i*1.71,a=i*Math.PI*2/16,r=26+Math.sin(phase)*5;
   const x=Math.cos(a)*r,y=Math.sin(a)*r,w=8+Math.sin(phase*1.3)*3,h=27+Math.sin(phase*.8+i)*14;
   const drift=Math.sin(phase+i*.8)*15+Math.sin(phase*2.3)*4;
   const gradient=ctx.createLinearGradient(x,y+7,x+drift,y-h);gradient.addColorStop(0,'#ff9c4fa8');gradient.addColorStop(.2,'#ff582cc4');gradient.addColorStop(.48,'#ef231abd');gradient.addColorStop(.78,'#b40d1555');gradient.addColorStop(1,'#8a081000');
   ctx.fillStyle=gradient;ctx.shadowColor='#ed2415';ctx.shadowBlur=7;ctx.beginPath();ctx.moveTo(x-w,y+5);ctx.bezierCurveTo(x-w*2,y-h*.4,x+drift-w,y-h*.8,x+drift,y-h);ctx.bezierCurveTo(x+drift+w*.4,y-h*.5,x+w*1.7,y-h*.35,x+w,y+5);ctx.quadraticCurveTo(x,y+10,x-w,y+5);ctx.fill();
  }
  ctx.shadowBlur=0;ctx.strokeStyle='#ffcf9366';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.stroke();ctx.restore();
 }
 function draw(now){frame=0;const dt=Math.min(.04,(now-last)/1000);last=now;ctx.clearRect(0,0,innerWidth,innerHeight);if(document.hidden){stopCrackle();particles=[];return}if(targeting&&targeting.family!=='meteor'&&!settings.reduced){const source=locate(targeting.uid,targeting.owner),end=targeting.target?locate(targeting.target,targeting.owner):pointer;const fire=targeting.family==='fireball';if(fire){flameHalo(end,now,1.15)}for(let i=0;i<2;i++){for(const center of fire?[end]:[source,end]){const a=now*.008+i*3;particle({x:center.x+Math.cos(a)*19,y:center.y+Math.sin(a)*16,vx:Math.random()*12-6,vy:fire?-35:-15,color:targeting.color,size:fire?4:2,shape:fire?'ember':'star',life:.4})}}}
  ctx.globalCompositeOperation='lighter';const survivors=[];for(const p of particles){if(now<p.born){survivors.push(p);continue}p.age=Math.max(0,(now-p.born)/1000);const t=p.age/p.life;if(t>=1){p.hit?.();continue}if(p.from){p.x=p.from.x+(p.to.x-p.from.x)*t;p.y=p.from.y+(p.to.y-p.from.y)*t;if(!settings.reduced)particle({x:p.x,y:p.y,vx:Math.random()*25-12,vy:-25,color:p.color,size:p.shape==='meteor'?6:4,shape:'ember',life:.3})}else{p.x+=(p.vx||0)*dt;p.y+=(p.vy||0)*dt}ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=1-t;ctx.strokeStyle=p.color;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=settings.reduced?0:12;ctx.lineWidth=2;const radius=p.size;
   if(['ring','rune','wave','portal','roots','shield','crown'].includes(p.shape)){const r=radius+(settings.reduced?0:t*55);ctx.rotate(p.shape==='portal'?t*3:0);ctx.beginPath();if(p.shape==='shield'){ctx.moveTo(0,-r);ctx.lineTo(r*.8,-r*.4);ctx.lineTo(r*.6,r*.6);ctx.lineTo(0,r);ctx.lineTo(-r*.6,r*.6);ctx.lineTo(-r*.8,-r*.4);ctx.closePath()}else{ctx.ellipse(0,0,r,p.shape==='portal'?r*.5:r,0,0,Math.PI*2)}ctx.stroke();if(['rune','crown','roots'].includes(p.shape)){for(let i=0;i<8;i++){const a=i*Math.PI/4+t;ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);ctx.lineTo(Math.cos(a)*(r+9),Math.sin(a)*(r+9));ctx.stroke()}}}
   else if(p.shape==='meteor'||p.shape==='projectile'){const angle=Math.atan2(p.to.y-p.from.y,p.to.x-p.from.x);ctx.rotate(angle);const gradient=ctx.createLinearGradient(-65,0,10,0);gradient.addColorStop(0,'transparent');gradient.addColorStop(.6,p.color);gradient.addColorStop(1,'#fff0b2');ctx.fillStyle=gradient;ctx.beginPath();ctx.moveTo(-70,0);ctx.lineTo(0,-radius);ctx.arc(0,0,radius,-Math.PI/2,Math.PI/2);ctx.closePath();ctx.fill();const core=ctx.createRadialGradient(-2,0,1,0,0,radius);core.addColorStop(0,'#fff6cd');core.addColorStop(.35,'#ffd065');core.addColorStop(.7,'#ff451e');core.addColorStop(1,'#b61114aa');ctx.fillStyle=core;ctx.beginPath();ctx.arc(0,0,radius,0,Math.PI*2);ctx.fill();if(p.shape==='meteor'){ctx.shadowBlur=3;ctx.fillStyle='#35211b';ctx.strokeStyle='#ff772f';ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<9;i++){const a=i*Math.PI*2/9,r=radius*(i%2?.66:.81);if(i)ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);else ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#f8a645';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-radius*.5,-radius*.2);ctx.lineTo(0,radius*.1);ctx.lineTo(radius*.4,-radius*.45);ctx.moveTo(0,radius*.1);ctx.lineTo(radius*.15,radius*.65);ctx.stroke()}}
   else if(['leaf','page','shard','star'].includes(p.shape)){ctx.rotate(p.age*3);ctx.beginPath();ctx.moveTo(0,-radius*2);ctx.lineTo(radius,0);ctx.lineTo(0,radius*2);ctx.lineTo(-radius,0);ctx.closePath();ctx.fill()}
   else{ctx.beginPath();ctx.arc(0,0,radius*(1-t*.6),0,Math.PI*2);ctx.fill()}ctx.restore();survivors.push(p)}particles=survivors.slice(-650);ctx.globalCompositeOperation='source-over';if(particles.length||targeting&&!settings.reduced)frame=requestAnimationFrame(draw)
 }
 function clear(){particles=[];targeting=null;stopCrackle();marks.forEach(n=>n.remove());marks=[];residueLayer?.querySelectorAll('.spell-departing').forEach(n=>n.remove());ctx?.clearRect(0,0,innerWidth,innerHeight)}
 function configure(options){Object.assign(settings,options);if(!settings.sound||settings.reduced)stopCrackle();if(master)master.gain.setTargetAtTime(settings.sound?settings.volume:0,audio.currentTime,.02);if(settings.reduced)clear()}
 document.addEventListener('pointermove',e=>pointer={x:e.clientX,y:e.clientY});document.addEventListener('pointerdown',unlock);document.addEventListener('keydown',unlock);window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear()});
 return {consume,capture,setTarget,configure,clear,stats,settings,locate,get debug(){return {audio:audio?.state,family:targeting?.family,hidden:document.hidden,reduced:settings.reduced,sound:settings.sound}},get activeParticles(){return particles.length},get activeCrackle(){return !!crackle}};
})();
